### ISSUE TITLE
Any docs in writing DSL for using to use old data in the new style

### ISSUE THREAD

**Issue by eriko** [ledermann/rails-settings#34]
I like the new setup but I am trying to figure out how to migrate old data into the new style.

Do you have any thoughts on this.  I have both top level Settings[:xxx] and instance.settings .

**Comment by gmcnaughton** [comment]
@ledermann is a migration like this the recommended approach for using legacy data from 1.x?

All of our user settings under 1.x were raw values, not hashes (e.g., `user.settings["foo"] = true`).

After upgrading to 2.4.0, trying to read these settings with `user.settings(:foo)` raises errors like `ActiveRecord::SerializationTypeMismatch: Attribute was supposed to be a Hash, but was a TrueClass`.

Is there any way to continue using legacy settings data from 1.x?

**Comment by ledermann** [comment]
Can't reproduce, v1 is looong time ago :) 
For all kind of migrations maybe you can use `RailsSettings::SettingObject` to access and convert plain settings.
