### ISSUE TITLE
How would I implement this on the form?

### ISSUE THREAD

**Issue by mengqing** [ledermann/rails-settings#46]
Say I have an User model with some settings. How would I implement so that settings can be updated on the User form?

An example would be much appreciated. Looked through test but didn't find any

**Comment by kcpavan** [comment]
How to make this work with fields_for ?
@bengalamx did you found the solution ?

**Comment by mengqing** [comment]
@NicoBijl @kcpavan this should work
```ruby
<%= f.fields_for :preference, current_user.settings(:preference) do |fields| %>
```

**Comment by bengalamx** [comment]
Hi @kcpavan, yes i make it work with:

```ruby
<%= form_for(:settings, url: edit_registration_path(resource_name), html: { method: :put }) do |form| %>
    <%= form.fields_for :detail, current_user.settings(:detail) do |f| %>
        <%= f.label :phone, 'Phone' %>
        <%= f.text_field :phone %>
        <%= f.label :website, 'Website' %>
        <%= f.url_field :website %>
    <% end %>
    <%= form.submit "Save" %>
<% end %>
```

And editing the devise registrations controller:

```ruby
def update
    if params[:settings]
        params[:settings].each do |key, value|
            current_user.settings(key.to_sym).update_attributes! value
        end
        set_flash_message :notice, :updated
        redirect_to :back
    else
        ....
    end
end
```

Hope this helps!

**Comment by asocialconstruct** [comment]
How would this work without devise?  (@bengalamx, I assume from your SO Q/A about this that you're using devise?)  Based on this thread I've got the form up, but I can't figure out what path to use in the form_for line or what controller to put the def update above in.  Right now I've got it in a SettingsController, but I get either forbidden attribute errors or no Post path errors depending on the path in the form_for call.  It'd be nice to see a straight forward form update example in the Readme.

**Comment by asocialconstruct** [comment]
In case it's useful to someone else, with Rails 4.2.1 I ended up doing this in my SettingsController:

def update
  if setting_params
    setting_params.each do |key, value|
      @current_user.settings(key.to_sym).update_attributes! value
    end
    flash[:success] = "Settings updated!"
    redirect_to request.referrer
  else
    render 'edit'
  end
end

def setting_params
  params.require(:settings).permit(dashboard: :theme)
end
