### ISSUE TITLE
Could not find generator rails_settings:migration

### ISSUE THREAD

**Issue by garethburrows** [ledermann/rails-settings#54]
Hi

could use a hand getting up and running. Have installed the gem with bundle but cannot run the migration file. Then try to run 

      rails g rails_settings:migration

but receive an error of 

      Could not find generator rails_settings:migration

Running rails 3, Ruby 1.9.3, but I've also tried this in a rails 4 environment on my machine. I've tried creating the migration manually and running it, which works, but then if I add the code
      	
      has_settings :dashboard, :calendar

to the Article model, and then fire up the server and console, If I try to examine the Article model, it reports

      NoMethodError: undefined method `has_settings' for #<Class:0x007fb4ab51ee08>

**Comment by sqlninja** [comment]
I am having this same issue...
ruby 2.5.0p0
rails 5.1.6
ledermann-rails-settings 2.4.3

running:
`rails g rails_settings:migration`
yields

> Running via Spring preloader in process 56042
> Could not find generator 'rails_settings:migration'. Maybe you meant 'active_record:migration', 'test_unit:integration' or 'migration'

**Comment by sqlninja** [comment]
That got it thanks
