### ISSUE TITLE
Better check for mass assignment?

### ISSUE THREAD

**Issue by randallb** [ledermann/rails-settings#59]
We're using rails 4, but we're using the `protected_attributes` gem to handle the upgrade. 

I currently get an error:

    ActiveModel::MassAssignmentSecurity::Error: Can't mass-assign protected attributes for RailsSettings::SettingObject: var, target

Not sure how to fix. Tried some stuff but it didn't work. If you tell me where to go to fix, I can try to fix.

**Comment by ledermann** [comment]
Hi all, please see #65 for a fix
