### ISSUE TITLE
Incompatible with protected_attributes gem

### ISSUE THREAD

**Issue by olliebennett** [ledermann/rails-settings#65]
Reproduced with `Rails 4.2.1` and `ledermann-rails-settings (2.3.0)`.

With the official [protected_attributes](https://github.com/rails/protected_attributes) gem (v 1.0.9) installed (and related usage of `attr_accessible`), the following error is logged:
```
WARNING: Can't mass-assign protected attributes for RailsSettings::SettingObject: var, target app/views/my_view.html.erb:48:in `block in ..._app_views_myview_html_erb___...'
```

This warning (as I'm sure you know) is commonly encountered with the `protected_attributes` gem when attempting to modify a resource property without defining that property to be `attr_accessible`. It's possible there's nothing we can do about it in this case, however I suspect that we could use feature detection in place of the Rails version comparison that happens in setting_object.rb on [this line](https://github.com/ledermann/rails-settings/blob/6f908a94ef8a5eaf147da442c8d8e0aded9c2aa4/lib/rails-settings/setting_object.rb#L21).

Perhaps mine is not a common use-case. The "best" solution is arguably to refactor and remove the `protected_attributes` gem and any reference to `attr_accessible` when using Rails 4 (this does indeed solve the problem, but is too great a refactor in our case).

**Comment by ledermann** [comment]
@olliebennett: I have pushed a fix to this issue. As you proposed, the Rails version check is replaced by feature detection. Does this work for you?

**Comment by olliebennett** [comment]
Hi Georg, yep - this works perfectly. Thanks

I'm using the following in my `Gemfile` until it's released:
```
gem 'ledermann-rails-settings', git: 'https://github.com/ledermann/rails-settings', ref: '18fd6dffca3f6e191c8b6c19657cfa14fb55670f'
```

**Comment by ledermann** [comment]
@olliebennett: Thanks for Feedback. I will publish a new release in a few days.
