### ISSUE TITLE
Version 2.4.x does not work with Rails 3

### ISSUE THREAD

**Issue by justinmiller61** [ledermann/rails-settings#73]
The README still says that Rails 3 is supported. Version 2.4.0 no longer checks the Rails version and instead uses feature detection to see if the protected_attributes gem was included. But protected_attributes is specifically for Rails >= 4 right?

So is Rails 3 no longer supported? If that's the answer, that's fine, albeit not ideal.

**Comment by ledermann** [comment]
Rails 3.1 or greater (not 3.0!) is supported - as stated in the [README](https://github.com/ledermann/rails-settings/blob/master/README.md) and the [gemspec](/ledermann/rails-settings/blob/master/rails-settings.gemspec). Tests on Travis are [running fine with Rails 3.1.12](https://travis-ci.org/ledermann/rails-settings/jobs/115642362). 

I can't see any problems regarding the Rails 3 support. Can you tell me more about your issues with Rails 3?

**Comment by justinmiller61** [comment]
We're running Rails 3.2. I get the "Can't mass-assign protected attributes var, target" error.

I was looking at this commit, specifically settings_object.rb: https://github.com/ledermann/rails-settings/commit/18fd6dffca3f6e191c8b6c19657cfa14fb55670f

In the prior version, the check for the Rails version would have executed that condition. Now, since it was replaced with the check for ProtectedAttributes (which we're not using), it no longer executes. That may not be relevant, but at a glance, it was the first thing that stood out.

**Comment by ledermann** [comment]
You are right. It seems the gem fails with Rails 3.x using `attr_accessible` which is not covered by the tests. Checking for `ProtectedAttributes` is not enough. What do you think about replacing

`if defined?(ProtectedAttributes)`
by
`if ActiveRecord::Base.respond_to?(:attr_accessible)`

Would this be helpful?

**Comment by justinmiller61** [comment]
Yep. That seems reasonable to me. Thanks!

**Comment by ledermann** [comment]
@justinmiller61 Just pushed some fixes. Please, could you check if the latest source works for you?

**Comment by justinmiller61** [comment]
Sure, I'll try and give it a go over the weekend.
