### ISSUE TITLE
Upgrade from v1 to v2

### ISSUE THREAD

**Issue by dwarfmondo** [ledermann/rails-settings#77]
Hello,

I'm attempting to upgrade from v1 to the latest version (v2.4.2) of the gem and I'm having trouble converting the code. Can someone tell me how I can convert the following code to work with the v2 API?

v1:

```ruby
# model
class Client < ActiveRecord::Base
  has_settings
end

# config/initializers/settings.rb
Settings.defaults[:sidebar_position] = 'expanded'

# view
current_client.settings.sidebar_position

# controller action to save position
current_client.settings.sidebar_position = params[:sidebar_position] == 'expanded' ? 'expanded' : 'collapsed'
```

Any help will be greatly appreciated! Thanks!

**Comment by ledermann** [comment]
I suggest to use the following:

```ruby
class Client < ActiveRecord::Base
  has_settings do |s|
    s.key :sidebar, :defaults => { :position => 'expanded' }
  end
end

# config/initializers/settings.rb
# not needed

# view
current_client.settings(:sidebar).position

# controller action to save position
current_client.settings(:sidebar).update_attributes! :position => (params[:sidebar_position] == 'expanded' ? 'expanded' : 'collapsed')
```

A database migration is needed to respect the added namespace.

**Comment by dwarfmondo** [comment]
Thank you. What is the format of the new namespace? For instance, the current `var` column in v1 is `sidebar_position`. Will it be `sidebar.position` in v2?
